### ISSUE TITLE
GitHub integration for composer-lock-diff corrupts PR description

### ISSUE THREAD

**Issue by YesCT** [Lullabot/drainpipe#186]
The current composer-lock-diff workflow uses sed to edit the description. Replacing newlines. There seem to be many testing situations that need to be considered.

https://github.com/Lullabot/drainpipe/issues/99 added the integration. And https://github.com/Lullabot/drainpipe/issues/181 tried to improve things, but resulted in newlines being stripped from PR descriptions.

**Comment by YesCT** [comment]
@marcoscano Posting as a comment instead of editing the description (first comment) is another approach I was thinking about also.

The downside, is that it makes a lot of emails, one for each new comment.

This means folks on the project will need to set up email filters to ignore or move emails to folders.

But the up side, with a new comment, no risk of messing up other text (since it isn't editing the description).

cc @justafish

**Comment by deviantintegral** [comment]
> Posting as a comment instead of editing the description (first comment) is another approach I was thinking about also.

> The downside, is that it makes a lot of emails, one for each new comment.

Yeah, if I remember right tugboat at least deletes the old comment before posting a new one.

I'm glad that we have html comment markers to simplify updates. This feels like the sort of thing that is worth tests around:

1. The initial adding of a table to a comment.
2. Updating a table with new composer data.
3. What happens if somehow there's _two_ tables with the html comment markers, or if the comment markers get reversed.
4. Removing the table if a PR undoes it's composer changes while keeping others.
5. Ensuring that the final generated text has appropriate line endings.

**Comment by justafish** [comment]
Fixed in #205
