### ISSUE TITLE
Add a test for untracked files

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#225]

**Comment by deviantintegral** [comment]
I think we need to describe what we want to implement here. There's an open PR but it's been stalled since August.

I'll say that I've seen a variant of this sort of test on most projects I've worked on over the past few years. However, there's also been cases where I've seen exclusions that are outside of typical gitignore files (usually filtered with `grep -v` or similar). I think it'd be good for us to define how and if we want to support those sort of excludes. I wonder if we can do a custom ignore file or something.

**Comment by beto-aveiga** [comment]
@deviantintegral : "a custom ignore file." Isn't it like having 2 sources of truth? Do you see any drawbacks to sticking to the `.gitignore` file exclusively?

> I've seen exclusions that are outside of typical gitignore files

I'm wondering what these exclusions were. Would you please provide a few examples?
