### ISSUE TITLE
Drainpipe-dev overwrites sites.php, destroying multisite configs

### ISSUE THREAD

**Issue by tess-ten7** [Lullabot/drainpipe#361]
Whenever using lullabot/drainpipe-dev, web/sites/sites.php is overwritten even if overwrite is set to false. This destroys multisite configs and renders Drainpipe useless for installing multisites.

**Comment by deviantintegral** [comment]
You should be able to set drupal-scaffold to not overwrite the file in composer.json like this:

```
        "drupal-scaffold": {
            "locations": {
                "web-root": "web/"
            },
            "file-mapping": {
                "[web-root]/sites/sites.php": false,
            },
            "allowed-packages": ["lullabot/drainpipe", "lullabot/drainpipe-dev", "pantheon-systems/drupal-integrations"],
            "gitignore": "true"
        },
```

https://github.com/drupal/core-composer-scaffold#excluding-scaffold-files

Does that work? I know it does on at least one project of ours, but it was set up over a year ago so it's possible things have drifted since then.

**Comment by deviantintegral** [comment]
See also: https://github.com/Lullabot/drainpipe/issues/372
