### ISSUE TITLE
sebastian/resource-operations is abandoned causing checks to fail

### ISSUE THREAD

**Issue by mrdavidburns** [Lullabot/drainpipe#478]
https://github.com/Lullabot/drainpipe/actions/runs/8273004200/job/22635924083?pr=477#step:10:66

```
[test:security] Found 1 abandoned package:
[test:security] +-------------------------------+----------------------------------------------------------------------------------+
[test:security] | Abandoned Package             | Suggested Replacement                                                            |
[test:security] +-------------------------------+----------------------------------------------------------------------------------+
[test:security] | sebastian/resource-operations | none                                                                             |
[test:security] +-------------------------------+----------------------------------------------------------------------------------+
```

**Comment by davereid** [comment]
```
composer why sebastian/resource-operations
phpunit/phpunit 9.6.17 requires sebastian/resource-operations (^3.0.3)
```

I also found https://github.com/sebastianbergmann/phpunit/issues/4828 which was from 2021?? But the repository was marked as archived again without adding `abandoned: false` to that repository recently again on March 13.

I propose that we add --no-dev to the audit commands to avoid security vulnerabilities in dev dependencies and only focus on production ones since that is the code that gets deployed.

**Comment by davereid** [comment]
Looks like the maintainer finally added `abandoned: false` and re-archived in https://github.com/sebastianbergmann/phpunit/issues/4828, so I think this should be resolved.

**Comment by davereid** [comment]
Confirmed this is fixed.
